name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build standalone EXE
        run: |
          pyinstaller --onefile --name deepseek-bot --add-data "config.py;." main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-windows-exe
          path: dist\deepseek-bot.exe

