name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install alpha discord.py-self first
          pip install git+https://github.com/dolfies/discord.py-self@master#egg=discord.py-self[voice,speed]
          # then the rest
          pip install -r requirements.txt pyinstaller pyinstaller-hooks-contrib

      - name: Build standalone EXE
        shell: bash
        run: |
          pyinstaller --onefile --name deepseek-bot \
            --add-data=config.py:. \
            --collect-all=openai \
            --collect-all=discord \
            --collect-all=sentence_transformers \
            --collect-all=torch \
            --collect-all=rich \
            main.py

      - name: Upload EXE + config
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-windows-release
          path: |
            dist/deepseek-bot.exe
            dist/config.py
