jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # …

      - name: Build standalone EXE
        shell: bash
        run: |
          pyinstaller \
            --onefile \
            --name deepseek-bot \
            --add-data=config.py;. \
            --collect-all=openai \
            --collect-all=discord \
            --collect-all=sentence_transformers \
            --collect-all=torch \
            --collect-all=rich \
            main.py
